// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aihr.assessment.api.Courses.Api.DbContexts;

#nullable disable

namespace aihr.assessment.api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220908103603_aihr_2")]
    partial class aihr_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("aihr.assessment.api.Courses.Api.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Hours")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hours = 8.0,
                            Name = "Blockchain and HR"
                        },
                        new
                        {
                            Id = 2,
                            Hours = 32.0,
                            Name = "Compensation and Benefits"
                        },
                        new
                        {
                            Id = 3,
                            Hours = 40.0,
                            Name = "Digital HR"
                        },
                        new
                        {
                            Id = 4,
                            Hours = 10.0,
                            Name = "Digital HR Strategy"
                        },
                        new
                        {
                            Id = 5,
                            Hours = 8.0,
                            Name = "Digital HR Transformation "
                        },
                        new
                        {
                            Id = 6,
                            Hours = 20.0,
                            Name = "Diversity and Inclusion"
                        },
                        new
                        {
                            Id = 7,
                            Hours = 12.0,
                            Name = "Employee Experience and Design Thinking"
                        },
                        new
                        {
                            Id = 8,
                            Hours = 6.0,
                            Name = "Employer Branding"
                        },
                        new
                        {
                            Id = 9,
                            Hours = 12.0,
                            Name = "Global Data Integrity"
                        },
                        new
                        {
                            Id = 24,
                            Hours = 15.0,
                            Name = "Hiring and Recruitment Strategy"
                        },
                        new
                        {
                            Id = 10,
                            Hours = 21.0,
                            Name = "HR Analytics Leader"
                        },
                        new
                        {
                            Id = 11,
                            Hours = 40.0,
                            Name = "HR Business Partner 2.0"
                        },
                        new
                        {
                            Id = 12,
                            Hours = 18.0,
                            Name = "HR Data Analyst"
                        },
                        new
                        {
                            Id = 13,
                            Hours = 12.0,
                            Name = "HR Data Science in R"
                        },
                        new
                        {
                            Id = 14,
                            Hours = 12.0,
                            Name = "HR Data Visualization"
                        },
                        new
                        {
                            Id = 15,
                            Hours = 40.0,
                            Name = "HR Metrics and Reporting"
                        },
                        new
                        {
                            Id = 16,
                            Hours = 30.0,
                            Name = "Learning and Development"
                        },
                        new
                        {
                            Id = 17,
                            Hours = 30.0,
                            Name = "Organizational Development"
                        },
                        new
                        {
                            Id = 18,
                            Hours = 40.0,
                            Name = "People Analytics"
                        },
                        new
                        {
                            Id = 19,
                            Hours = 15.0,
                            Name = "Statistics in HR"
                        },
                        new
                        {
                            Id = 20,
                            Hours = 34.0,
                            Name = "Strategic HR Leadership"
                        },
                        new
                        {
                            Id = 21,
                            Hours = 17.0,
                            Name = "Strategic HR Metrics"
                        },
                        new
                        {
                            Id = 22,
                            Hours = 40.0,
                            Name = "Talent Acquisition"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
